//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: orders.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `OrdersStreamServiceClient`, then call methods of this protocol to make API calls.
public protocol OrdersStreamServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: OrdersStreamServiceClientInterceptorFactoryProtocol? { get }

  func tradesStream(
    _ request: TradesStreamRequest,
    callOptions: CallOptions?,
    handler: @escaping (TradesStreamResponse) -> Void
  ) -> ServerStreamingCall<TradesStreamRequest, TradesStreamResponse>
}

extension OrdersStreamServiceClientProtocol {
  public var serviceName: String {
    return "tinkoff.public.invest.api.contract.v1.OrdersStreamService"
  }

  ///Stream сделок пользователя
  ///
  /// - Parameters:
  ///   - request: Request to send to TradesStream.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  public func tradesStream(
    _ request: TradesStreamRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (TradesStreamResponse) -> Void
  ) -> ServerStreamingCall<TradesStreamRequest, TradesStreamResponse> {
    return self.makeServerStreamingCall(
      path: "/tinkoff.public.invest.api.contract.v1.OrdersStreamService/TradesStream",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTradesStreamInterceptors() ?? [],
      handler: handler
    )
  }
}

public protocol OrdersStreamServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'tradesStream'.
  func makeTradesStreamInterceptors() -> [ClientInterceptor<TradesStreamRequest, TradesStreamResponse>]
}

public final class OrdersStreamServiceClient: OrdersStreamServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: OrdersStreamServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the tinkoff.public.invest.api.contract.v1.OrdersStreamService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: OrdersStreamServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Сервис предназначен для работы с торговыми поручениями:</br> **1**.
///выставление;</br> **2**. отмена;</br> **3**. получение статуса;</br> **4**.
///расчёт полной стоимости;</br> **5**. получение списка заявок.
///
/// Usage: instantiate `OrdersServiceClient`, then call methods of this protocol to make API calls.
public protocol OrdersServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: OrdersServiceClientInterceptorFactoryProtocol? { get }

  func postOrder(
    _ request: PostOrderRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<PostOrderRequest, PostOrderResponse>

  func cancelOrder(
    _ request: CancelOrderRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<CancelOrderRequest, CancelOrderResponse>

  func getOrderState(
    _ request: GetOrderStateRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<GetOrderStateRequest, OrderState>

  func getOrders(
    _ request: GetOrdersRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<GetOrdersRequest, GetOrdersResponse>

  func replaceOrder(
    _ request: ReplaceOrderRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<ReplaceOrderRequest, PostOrderResponse>
}

extension OrdersServiceClientProtocol {
  public var serviceName: String {
    return "tinkoff.public.invest.api.contract.v1.OrdersService"
  }

  ///Метод выставления заявки.
  ///
  /// - Parameters:
  ///   - request: Request to send to PostOrder.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func postOrder(
    _ request: PostOrderRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<PostOrderRequest, PostOrderResponse> {
    return self.makeUnaryCall(
      path: "/tinkoff.public.invest.api.contract.v1.OrdersService/PostOrder",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePostOrderInterceptors() ?? []
    )
  }

  ///Метод отмены биржевой заявки.
  ///
  /// - Parameters:
  ///   - request: Request to send to CancelOrder.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func cancelOrder(
    _ request: CancelOrderRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<CancelOrderRequest, CancelOrderResponse> {
    return self.makeUnaryCall(
      path: "/tinkoff.public.invest.api.contract.v1.OrdersService/CancelOrder",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCancelOrderInterceptors() ?? []
    )
  }

  ///Метод получения статуса торгового поручения.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetOrderState.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getOrderState(
    _ request: GetOrderStateRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<GetOrderStateRequest, OrderState> {
    return self.makeUnaryCall(
      path: "/tinkoff.public.invest.api.contract.v1.OrdersService/GetOrderState",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetOrderStateInterceptors() ?? []
    )
  }

  ///Метод получения списка активных заявок по счёту.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetOrders.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getOrders(
    _ request: GetOrdersRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<GetOrdersRequest, GetOrdersResponse> {
    return self.makeUnaryCall(
      path: "/tinkoff.public.invest.api.contract.v1.OrdersService/GetOrders",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetOrdersInterceptors() ?? []
    )
  }

  ///Метод изменения выставленной заявки.
  ///
  /// - Parameters:
  ///   - request: Request to send to ReplaceOrder.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func replaceOrder(
    _ request: ReplaceOrderRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<ReplaceOrderRequest, PostOrderResponse> {
    return self.makeUnaryCall(
      path: "/tinkoff.public.invest.api.contract.v1.OrdersService/ReplaceOrder",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeReplaceOrderInterceptors() ?? []
    )
  }
}

public protocol OrdersServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'postOrder'.
  func makePostOrderInterceptors() -> [ClientInterceptor<PostOrderRequest, PostOrderResponse>]

  /// - Returns: Interceptors to use when invoking 'cancelOrder'.
  func makeCancelOrderInterceptors() -> [ClientInterceptor<CancelOrderRequest, CancelOrderResponse>]

  /// - Returns: Interceptors to use when invoking 'getOrderState'.
  func makeGetOrderStateInterceptors() -> [ClientInterceptor<GetOrderStateRequest, OrderState>]

  /// - Returns: Interceptors to use when invoking 'getOrders'.
  func makeGetOrdersInterceptors() -> [ClientInterceptor<GetOrdersRequest, GetOrdersResponse>]

  /// - Returns: Interceptors to use when invoking 'replaceOrder'.
  func makeReplaceOrderInterceptors() -> [ClientInterceptor<ReplaceOrderRequest, PostOrderResponse>]
}

public final class OrdersServiceClient: OrdersServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: OrdersServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the tinkoff.public.invest.api.contract.v1.OrdersService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: OrdersServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol OrdersStreamServiceProvider: CallHandlerProvider {
  var interceptors: OrdersStreamServiceServerInterceptorFactoryProtocol? { get }

  ///Stream сделок пользователя
  func tradesStream(request: TradesStreamRequest, context: StreamingResponseCallContext<TradesStreamResponse>) -> EventLoopFuture<GRPCStatus>
}

extension OrdersStreamServiceProvider {
  public var serviceName: Substring { return "tinkoff.public.invest.api.contract.v1.OrdersStreamService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "TradesStream":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<TradesStreamRequest>(),
        responseSerializer: ProtobufSerializer<TradesStreamResponse>(),
        interceptors: self.interceptors?.makeTradesStreamInterceptors() ?? [],
        userFunction: self.tradesStream(request:context:)
      )

    default:
      return nil
    }
  }
}

public protocol OrdersStreamServiceServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'tradesStream'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeTradesStreamInterceptors() -> [ServerInterceptor<TradesStreamRequest, TradesStreamResponse>]
}
/// Сервис предназначен для работы с торговыми поручениями:</br> **1**.
///выставление;</br> **2**. отмена;</br> **3**. получение статуса;</br> **4**.
///расчёт полной стоимости;</br> **5**. получение списка заявок.
///
/// To build a server, implement a class that conforms to this protocol.
public protocol OrdersServiceProvider: CallHandlerProvider {
  var interceptors: OrdersServiceServerInterceptorFactoryProtocol? { get }

  ///Метод выставления заявки.
  func postOrder(request: PostOrderRequest, context: StatusOnlyCallContext) -> EventLoopFuture<PostOrderResponse>

  ///Метод отмены биржевой заявки.
  func cancelOrder(request: CancelOrderRequest, context: StatusOnlyCallContext) -> EventLoopFuture<CancelOrderResponse>

  ///Метод получения статуса торгового поручения.
  func getOrderState(request: GetOrderStateRequest, context: StatusOnlyCallContext) -> EventLoopFuture<OrderState>

  ///Метод получения списка активных заявок по счёту.
  func getOrders(request: GetOrdersRequest, context: StatusOnlyCallContext) -> EventLoopFuture<GetOrdersResponse>

  ///Метод изменения выставленной заявки.
  func replaceOrder(request: ReplaceOrderRequest, context: StatusOnlyCallContext) -> EventLoopFuture<PostOrderResponse>
}

extension OrdersServiceProvider {
  public var serviceName: Substring { return "tinkoff.public.invest.api.contract.v1.OrdersService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "PostOrder":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<PostOrderRequest>(),
        responseSerializer: ProtobufSerializer<PostOrderResponse>(),
        interceptors: self.interceptors?.makePostOrderInterceptors() ?? [],
        userFunction: self.postOrder(request:context:)
      )

    case "CancelOrder":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<CancelOrderRequest>(),
        responseSerializer: ProtobufSerializer<CancelOrderResponse>(),
        interceptors: self.interceptors?.makeCancelOrderInterceptors() ?? [],
        userFunction: self.cancelOrder(request:context:)
      )

    case "GetOrderState":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<GetOrderStateRequest>(),
        responseSerializer: ProtobufSerializer<OrderState>(),
        interceptors: self.interceptors?.makeGetOrderStateInterceptors() ?? [],
        userFunction: self.getOrderState(request:context:)
      )

    case "GetOrders":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<GetOrdersRequest>(),
        responseSerializer: ProtobufSerializer<GetOrdersResponse>(),
        interceptors: self.interceptors?.makeGetOrdersInterceptors() ?? [],
        userFunction: self.getOrders(request:context:)
      )

    case "ReplaceOrder":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<ReplaceOrderRequest>(),
        responseSerializer: ProtobufSerializer<PostOrderResponse>(),
        interceptors: self.interceptors?.makeReplaceOrderInterceptors() ?? [],
        userFunction: self.replaceOrder(request:context:)
      )

    default:
      return nil
    }
  }
}

public protocol OrdersServiceServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'postOrder'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makePostOrderInterceptors() -> [ServerInterceptor<PostOrderRequest, PostOrderResponse>]

  /// - Returns: Interceptors to use when handling 'cancelOrder'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCancelOrderInterceptors() -> [ServerInterceptor<CancelOrderRequest, CancelOrderResponse>]

  /// - Returns: Interceptors to use when handling 'getOrderState'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetOrderStateInterceptors() -> [ServerInterceptor<GetOrderStateRequest, OrderState>]

  /// - Returns: Interceptors to use when handling 'getOrders'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetOrdersInterceptors() -> [ServerInterceptor<GetOrdersRequest, GetOrdersResponse>]

  /// - Returns: Interceptors to use when handling 'replaceOrder'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeReplaceOrderInterceptors() -> [ServerInterceptor<ReplaceOrderRequest, PostOrderResponse>]
}
