//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: stoporders.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Сервис предназначен для работы со стоп-заявками:</br> **1**.
///выставление;</br> **2**. отмена;</br> **3**. получение списка стоп-заявок.
///
/// Usage: instantiate `StopOrdersServiceClient`, then call methods of this protocol to make API calls.
public protocol StopOrdersServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: StopOrdersServiceClientInterceptorFactoryProtocol? { get }

  func postStopOrder(
    _ request: PostStopOrderRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<PostStopOrderRequest, PostStopOrderResponse>

  func getStopOrders(
    _ request: GetStopOrdersRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<GetStopOrdersRequest, GetStopOrdersResponse>

  func cancelStopOrder(
    _ request: CancelStopOrderRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<CancelStopOrderRequest, CancelStopOrderResponse>
}

extension StopOrdersServiceClientProtocol {
  public var serviceName: String {
    return "tinkoff.public.invest.api.contract.v1.StopOrdersService"
  }

  ///Метод выставления стоп-заявки.
  ///
  /// - Parameters:
  ///   - request: Request to send to PostStopOrder.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func postStopOrder(
    _ request: PostStopOrderRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<PostStopOrderRequest, PostStopOrderResponse> {
    return self.makeUnaryCall(
      path: "/tinkoff.public.invest.api.contract.v1.StopOrdersService/PostStopOrder",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePostStopOrderInterceptors() ?? []
    )
  }

  ///Метод получения списка активных стоп заявок по счёту.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetStopOrders.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getStopOrders(
    _ request: GetStopOrdersRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<GetStopOrdersRequest, GetStopOrdersResponse> {
    return self.makeUnaryCall(
      path: "/tinkoff.public.invest.api.contract.v1.StopOrdersService/GetStopOrders",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetStopOrdersInterceptors() ?? []
    )
  }

  ///Метод отмены стоп-заявки.
  ///
  /// - Parameters:
  ///   - request: Request to send to CancelStopOrder.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func cancelStopOrder(
    _ request: CancelStopOrderRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<CancelStopOrderRequest, CancelStopOrderResponse> {
    return self.makeUnaryCall(
      path: "/tinkoff.public.invest.api.contract.v1.StopOrdersService/CancelStopOrder",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCancelStopOrderInterceptors() ?? []
    )
  }
}

public protocol StopOrdersServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'postStopOrder'.
  func makePostStopOrderInterceptors() -> [ClientInterceptor<PostStopOrderRequest, PostStopOrderResponse>]

  /// - Returns: Interceptors to use when invoking 'getStopOrders'.
  func makeGetStopOrdersInterceptors() -> [ClientInterceptor<GetStopOrdersRequest, GetStopOrdersResponse>]

  /// - Returns: Interceptors to use when invoking 'cancelStopOrder'.
  func makeCancelStopOrderInterceptors() -> [ClientInterceptor<CancelStopOrderRequest, CancelStopOrderResponse>]
}

public final class StopOrdersServiceClient: StopOrdersServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: StopOrdersServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the tinkoff.public.invest.api.contract.v1.StopOrdersService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: StopOrdersServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Сервис предназначен для работы со стоп-заявками:</br> **1**.
///выставление;</br> **2**. отмена;</br> **3**. получение списка стоп-заявок.
///
/// To build a server, implement a class that conforms to this protocol.
public protocol StopOrdersServiceProvider: CallHandlerProvider {
  var interceptors: StopOrdersServiceServerInterceptorFactoryProtocol? { get }

  ///Метод выставления стоп-заявки.
  func postStopOrder(request: PostStopOrderRequest, context: StatusOnlyCallContext) -> EventLoopFuture<PostStopOrderResponse>

  ///Метод получения списка активных стоп заявок по счёту.
  func getStopOrders(request: GetStopOrdersRequest, context: StatusOnlyCallContext) -> EventLoopFuture<GetStopOrdersResponse>

  ///Метод отмены стоп-заявки.
  func cancelStopOrder(request: CancelStopOrderRequest, context: StatusOnlyCallContext) -> EventLoopFuture<CancelStopOrderResponse>
}

extension StopOrdersServiceProvider {
  public var serviceName: Substring { return "tinkoff.public.invest.api.contract.v1.StopOrdersService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "PostStopOrder":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<PostStopOrderRequest>(),
        responseSerializer: ProtobufSerializer<PostStopOrderResponse>(),
        interceptors: self.interceptors?.makePostStopOrderInterceptors() ?? [],
        userFunction: self.postStopOrder(request:context:)
      )

    case "GetStopOrders":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<GetStopOrdersRequest>(),
        responseSerializer: ProtobufSerializer<GetStopOrdersResponse>(),
        interceptors: self.interceptors?.makeGetStopOrdersInterceptors() ?? [],
        userFunction: self.getStopOrders(request:context:)
      )

    case "CancelStopOrder":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<CancelStopOrderRequest>(),
        responseSerializer: ProtobufSerializer<CancelStopOrderResponse>(),
        interceptors: self.interceptors?.makeCancelStopOrderInterceptors() ?? [],
        userFunction: self.cancelStopOrder(request:context:)
      )

    default:
      return nil
    }
  }
}

public protocol StopOrdersServiceServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'postStopOrder'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makePostStopOrderInterceptors() -> [ServerInterceptor<PostStopOrderRequest, PostStopOrderResponse>]

  /// - Returns: Interceptors to use when handling 'getStopOrders'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetStopOrdersInterceptors() -> [ServerInterceptor<GetStopOrdersRequest, GetStopOrdersResponse>]

  /// - Returns: Interceptors to use when handling 'cancelStopOrder'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCancelStopOrderInterceptors() -> [ServerInterceptor<CancelStopOrderRequest, CancelStopOrderResponse>]
}
